using DataBuildingLayer;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Hosting;

namespace SIS_Operational_Reports.Common
{
    /// <summary>
    /// Builds HTML email body for Fresh Water Report. Uses FreshWaterReport.html template when available.
    /// Uses FreshWaterReport data model with port, meter reading, and quantity details.
    /// </summary>
    public static class FreshWaterReportEmailTemplate
    {
        private const string DateFormat = "dd-MMM-yyyy";
        private const string DateTimeFormat = "dd-MMM-yyyy HH:mm";
        private const string TemplatePath = "~/Templates/FreshWaterReport.html";

        private static string V(object o) => o == null || o == DBNull.Value || string.IsNullOrWhiteSpace(o.ToString()) ? "-" : o.ToString().Trim();
        private static string V(decimal? d) => d.HasValue ? (d.Value == Math.Truncate(d.Value) ? d.Value.ToString("0") : d.Value.ToString("0.000")) : "-";
        private static string V(DateTime? dt) => dt.HasValue ? dt.Value.ToString(DateFormat) : "-";
        private static string Vdt(DateTime dt) => dt != DateTime.MinValue ? dt.ToString(DateTimeFormat) : "-";

        /// <param name="reportId">When set (from export filename R{id}), used to fetch the fresh water report by ID.</param>
        public static string BuildHtml(int vesselId, string datePart, int? reportId = null)
        {
            if (!reportId.HasValue || reportId.Value <= 0) return null;

            int id = reportId.Value;
            var fwRList = CommonMethods.editFreshWaterRList(id, vesselId, "FreshWaterReport");
            var fwRBind = fwRList?.Where(x => x.Id == id).FirstOrDefault();
            if (fwRBind == null) return null;

            string vesselName = CommonClass.GetVesselNamesByImoNo(vesselId.ToString());
            if (string.IsNullOrEmpty(vesselName)) vesselName = "Vessel " + vesselId;

            string templatePath = null;
            try { templatePath = HostingEnvironment.MapPath(TemplatePath); } catch { }
            if (string.IsNullOrEmpty(templatePath))
            {
                try { templatePath = HttpContext.Current?.Server?.MapPath(TemplatePath); } catch { }
            }
            if (!string.IsNullOrEmpty(templatePath) && File.Exists(templatePath))
            {
                string template = File.ReadAllText(templatePath);
                return ApplyTemplate(template, fwRBind, vesselName);
            }
            return BuildHtmlInline(fwRBind, vesselName);
        }

        private static string ApplyTemplate(string template, FreshWaterReport r, string vesselName)
        {
            var sb = new StringBuilder();
            sb.Append(KvRow("Port", r.PortName)).Append(KvRow("Facility Name", r.Facility_Name));
            sb.Append(KvRow("Vendor Details", r.VendorDetails));
            sb.Append(KvRow("Received Date", Vdt(r.Received_Date)));
            string headerRows = sb.ToString();
            sb.Clear();

            sb.Append(KvRow("Initial Meter Reading (MT)", r.Intial_Meter_Reading_MT_supplied));
            sb.Append(KvRow("Final Meter Reading (MT)", r.Final_Meter_Reading_MT));
            sb.Append(KvRow("Difference in Meter Reading (MT)", r.Difference_in_Meter_Reading_MT));
            sb.Append(KvRow("Qty Supplied (MT)", r.QTY_supplied_MT));
            string meterRows = sb.ToString();

            return template
                .Replace("{{VESSEL_NAME}}", V(vesselName))
                .Replace("{{REPORT_DATE}}", Vdt(r.Received_Date))
                .Replace("{{HEADER_ROWS}}", headerRows)
                .Replace("{{METER_ROWS}}", meterRows)
                .Replace("{{FILE_NAME}}", V(r.File_Name));
        }

        private static string BuildHtmlInline(FreshWaterReport r, string vesselName)
        {
            var sb = new StringBuilder();
            sb.Append(@"<!DOCTYPE html><html><head><meta charset=""utf-8""></head><body style=""margin:0;padding:12px;font-family:Arial,sans-serif;font-size:12px;"">");
            sb.Append(@"<p style=""margin:0 0 12px 0;"">Hello,</p><p style=""margin:0 0 12px 0;"">Please note that this is an automated email generated by the system.</p>");
            sb.Append(@"<p style=""margin:0 0 12px 0;"">The Fresh Water Report for vessel ").Append(System.Web.HttpUtility.HtmlEncode(vesselName ?? "")).Append(@" dated ").Append(Vdt(r.Received_Date)).Append(@" has been successfully generated and is attached to this email in Excel format for your reference.</p>");
            sb.Append(@"<table style=""width:100%;min-width:1200px;max-width:1200px;border-collapse:collapse;border:1px solid #ccc;"">");

            // Fresh Water Details header
            sb.Append(@"<tr><td colspan=""8"" style=""padding:12px;background:#555;color:#fff;font-size:16px;font-weight:bold;text-align:center;"">Fresh Water Report - Details (").Append(V(vesselName)).Append(@")</td></tr>");
            sb.Append(@"<tr><td colspan=""8"" style=""padding:0;""><table style=""width:100%;border-collapse:collapse;table-layout:fixed;""><col style=""width:45%;min-width:280px""><col style=""width:55%"">");
            sb.Append(KvRow("Port", r.PortName)).Append(KvRow("Facility Name", r.Facility_Name));
            sb.Append(KvRow("Vendor Details", r.VendorDetails));
            sb.Append(KvRow("Received Date", Vdt(r.Received_Date)));
            sb.Append(@"</table></td></tr>");

            // Meter Reading & Quantity
            sb.Append(@"<tr><td colspan=""8"" style=""padding:10px 8px;background:#555;color:#fff;font-weight:bold;text-align:center;"">Meter Reading & Quantity</td></tr>");
            sb.Append(@"<tr><td colspan=""8"" style=""padding:0;""><table style=""width:100%;border-collapse:collapse;table-layout:fixed;""><col style=""width:45%;min-width:280px""><col style=""width:55%"">");
            sb.Append(KvRow("Initial Meter Reading (MT)", r.Intial_Meter_Reading_MT_supplied));
            sb.Append(KvRow("Final Meter Reading (MT)", r.Final_Meter_Reading_MT));
            sb.Append(KvRow("Difference in Meter Reading (MT)", r.Difference_in_Meter_Reading_MT));
            sb.Append(KvRow("Qty Supplied (MT)", r.QTY_supplied_MT));
            sb.Append(@"</table></td></tr>");

            // Attached Document
            sb.Append(@"<tr><td colspan=""8"" style=""padding:10px 8px;background:#555;color:#fff;font-weight:bold;text-align:center;"">Attached Document</td></tr>");
            sb.Append(@"<tr><td colspan=""8"" style=""padding:0;""><table style=""width:100%;border-collapse:collapse;table-layout:fixed;""><col style=""width:45%;min-width:280px""><col style=""width:55%"">");
            sb.Append(KvRow("File Name", r.File_Name));
            sb.Append(@"</table></td></tr>");

            sb.Append(@"</table>");
            sb.Append(@"<p style=""margin:12px 0 0 0;"">Please note that this is a no-reply email, and responses to this mailbox are not monitored.</p>");
            sb.Append(@"<p style=""margin:4px 0 0 0;"">For any queries or assistance, please contact the concerned team through the designated communication channel.</p>");
            sb.Append(@"<p style=""margin:12px 0 0 0;"">Thank you,</p><p style=""margin:4px 0 0 0;"">Team SIS</p></body></html>");
            return sb.ToString();
        }

        /// <summary>Single label-value row for 2-column layout.</summary>
        private static string KvRow(string label, object value)
        {
            string v = (value is decimal || value is decimal?) ? V((decimal?)value) : V(value);
            return @"<tr><td class=""col-label"" style=""padding:6px 8px;border:1px solid #ccc;font-weight:bold;background:#f5f5f5;vertical-align:middle;white-space:nowrap;"">" + (label ?? "") + @"</td><td class=""col-value"" style=""padding:6px 8px;border:1px solid #ccc;vertical-align:middle;text-align:right;"">" + v + @"</td></tr>";
        }
    }
}
