using DataBuildingLayer;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Hosting;

namespace SIS_Operational_Reports.Common
{
    /// <summary>
    /// Builds HTML email body for Noon Report Allow. Uses NoonReportAllow.html template when available.
    /// Uses DailyNoonReportAllow data model with vessel, bypass date, and user details.
    /// </summary>
    public static class NoonReportAllowEmailTemplate
    {
        private const string DateFormat = "dd-MMM-yyyy";
        private const string TemplatePath = "~/Templates/NoonReportAllow.html";

        private static string V(object o) => o == null || o == DBNull.Value || string.IsNullOrWhiteSpace(o.ToString()) ? "-" : o.ToString().Trim();
        private static string V(DateTime? dt) => dt.HasValue ? dt.Value.ToString(DateFormat) : "-";

        /// <param name="reportId">When set (from export filename R{id}), used to fetch the noon report allow by ID.</param>
        public static string BuildHtml(int vesselId, string datePart, int? reportId = null)
        {
            if (!reportId.HasValue || reportId.Value <= 0) return null;

            int id = reportId.Value;

            // Fetch noon report allow details by ID
            string noonDate = "";
            string userName = "";
            try
            {
                using (SqlDataAdapter adp = new SqlDataAdapter("select Id, Vessel_Id, Noon_date, userName from NoonReport_allow where Id=" + id + " and IsActive=1", ConnectionBulder.con))
                {
                    DataTable dt = new DataTable();
                    adp.Fill(dt);
                    if (dt.Rows.Count > 0)
                    {
                        noonDate = dt.Rows[0]["Noon_date"]?.ToString() ?? "";
                        userName = dt.Rows[0]["userName"]?.ToString() ?? "";
                    }
                }
            }
            catch { }

            if (string.IsNullOrEmpty(noonDate)) return null;

            string vesselName = CommonClass.GetVesselNamesByImoNo(vesselId.ToString());
            if (string.IsNullOrEmpty(vesselName)) vesselName = "Vessel " + vesselId;

            string formattedDate = noonDate;
            DateTime d;
            if (DateTime.TryParse(noonDate, out d))
                formattedDate = d.ToString(DateFormat);

            string templatePath = null;
            try { templatePath = HostingEnvironment.MapPath(TemplatePath); } catch { }
            if (string.IsNullOrEmpty(templatePath))
            {
                try { templatePath = HttpContext.Current?.Server?.MapPath(TemplatePath); } catch { }
            }
            if (!string.IsNullOrEmpty(templatePath) && File.Exists(templatePath))
            {
                string template = File.ReadAllText(templatePath);
                return ApplyTemplate(template, vesselName, formattedDate, userName, id);
            }
            return BuildHtmlInline(vesselName, vesselId, formattedDate, userName, id);
        }

        private static string ApplyTemplate(string template, string vesselName, string noonDate, string userName, int id)
        {
            return template
                .Replace("{{VESSEL_NAME}}", V(vesselName))
                .Replace("{{NOON_DATE}}", V(noonDate))
                .Replace("{{USER_NAME}}", V(userName))
                .Replace("{{REPORT_ID}}", id.ToString());
        }

        private static string BuildHtmlInline(string vesselName, int vesselId, string noonDate, string userName, int id)
        {
            var sb = new StringBuilder();
            sb.Append(@"<!DOCTYPE html><html><head><meta charset=""utf-8""></head><body style=""margin:0;padding:12px;font-family:Arial,sans-serif;font-size:12px;"">");
            sb.Append(@"<p style=""margin:0 0 12px 0;"">Hello,</p><p style=""margin:0 0 12px 0;"">Please note that this is an automated email generated by the system.</p>");
            sb.Append(@"<p style=""margin:0 0 12px 0;"">The Noon Report Allow for vessel ").Append(System.Web.HttpUtility.HtmlEncode(vesselName ?? "")).Append(@" dated ").Append(V(noonDate)).Append(@" has been successfully generated and is attached to this email in Excel format for your reference.</p>");
            sb.Append(@"<table style=""width:100%;min-width:1200px;max-width:1200px;border-collapse:collapse;border:1px solid #ccc;"">");

            // Noon Report Allow Details header
            sb.Append(@"<tr><td colspan=""8"" style=""padding:12px;background:#555;color:#fff;font-size:16px;font-weight:bold;text-align:center;"">Noon Report Allow - Details (").Append(V(vesselName)).Append(@")</td></tr>");
            sb.Append(@"<tr><td colspan=""8"" style=""padding:0;""><table style=""width:100%;border-collapse:collapse;table-layout:fixed;""><col style=""width:45%;min-width:280px""><col style=""width:55%"">");
            sb.Append(KvRow("Vessel Name", vesselName));
            sb.Append(KvRow("Vessel ID (IMO No.)", vesselId));
            sb.Append(@"</table></td></tr>");

            // Bypass Date Details
            sb.Append(@"<tr><td colspan=""8"" style=""padding:10px 8px;background:#555;color:#fff;font-weight:bold;text-align:center;"">Bypass Date Details</td></tr>");
            sb.Append(@"<tr><td colspan=""8"" style=""padding:0;""><table style=""width:100%;border-collapse:collapse;table-layout:fixed;""><col style=""width:45%;min-width:280px""><col style=""width:55%"">");
            sb.Append(KvRow("Noon Report Allow Date", noonDate));
            sb.Append(KvRow("User Name", userName));
            sb.Append(KvRow("Report ID", id));
            sb.Append(@"</table></td></tr>");

            sb.Append(@"</table>");
            sb.Append(@"<p style=""margin:12px 0 0 0;"">Please note that this is a no-reply email, and responses to this mailbox are not monitored.</p>");
            sb.Append(@"<p style=""margin:4px 0 0 0;"">For any queries or assistance, please contact the concerned team through the designated communication channel.</p>");
            sb.Append(@"<p style=""margin:12px 0 0 0;"">Thank you,</p><p style=""margin:4px 0 0 0;"">Team SIS</p></body></html>");
            return sb.ToString();
        }

        /// <summary>Single label-value row for 2-column layout.</summary>
        private static string KvRow(string label, object value)
        {
            string v = V(value);
            return @"<tr><td class=""col-label"" style=""padding:6px 8px;border:1px solid #ccc;font-weight:bold;background:#f5f5f5;vertical-align:middle;white-space:nowrap;"">" + (label ?? "") + @"</td><td class=""col-value"" style=""padding:6px 8px;border:1px solid #ccc;vertical-align:middle;text-align:right;"">" + v + @"</td></tr>";
        }
    }
}
